name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: asreedh-apw-production
      url: https://asreedh-apw-production.herokuapp.com
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "asreedh-apw-production" # Must be unique in Heroku
          heroku_email: "sreedhara.aneesh@gmail.com"
          usedocker: true